package enumi;

public enum Sluzba {
	
	SLUZBA_OPSTE_MEDICINE, 
	SLUZBA_ZDRAVSTVENE_ZASTITE_DECE,
	STOMATOLOSKA_SLUZBA,
	SLUZBA_ZDRAVSTVENE_ZASTITE_RADNIKA,
	SLUZBA_ZA_PRAVNE_I_EKONOMSKE_POSLOVE,
	SLUZBA_ZA_TEHNICKE_POSLOVE

}
